# Compiler
CC = gcc

# Compiler flags
CFLAGS = -Wall -g

# Library files
LIB = huffman.c binary.c

# Output executable name
TARGET = huffman.out

all: main.c $(LIB)
	$(CC) -o $(TARGET) $(CFLAGS) main.c $(LIB)
